# Generated by Django 5.2.14 on 2026-05-29 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGolpe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da categoria')),
            ],
            options={
                'verbose_name': 'Categoria de Golpe',
                'verbose_name_plural': 'Categorias de Golpes',
            },
        ),
        migrations.CreateModel(
            name='DicaSeguranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Dica de Segurança',
                'verbose_name_plural': 'Dicas de Segurança',
            },
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da plataforma')),
            ],
            options={
                'verbose_name': 'Plataforma',
                'verbose_name_plural': 'Plataformas',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do tipo de usuário')),
            ],
            options={
                'verbose_name': 'Tipo de Usuário',
                'verbose_name_plural': 'Tipos de Usuários',
            },
        ),
        migrations.CreateModel(
            name='GolpeDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título do golpe')),
                ('descricao', models.TextField(verbose_name='Descrição do golpe')),
                ('nivel_risco', models.CharField(max_length=50, verbose_name='Nível de risco')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoriagolpe', verbose_name='Categoria do golpe')),
            ],
            options={
                'verbose_name': 'Golpe Digital',
                'verbose_name_plural': 'Golpes Digitais',
            },
        ),
        migrations.CreateModel(
            name='LinkSuspeito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('nivel_perigo', models.CharField(max_length=50, verbose_name='Nível de perigo')),
                ('data_cadastro', models.DateTimeField(verbose_name='Data de cadastro')),
                ('golpe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.golpedigital', verbose_name='Golpe digital')),
            ],
            options={
                'verbose_name': 'Link Suspeito',
                'verbose_name_plural': 'Links Suspeitos',
            },
        ),
        migrations.CreateModel(
            name='MensagemFraudulenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('nivel_risco', models.CharField(max_length=50, verbose_name='Nível de risco')),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.plataforma', verbose_name='Plataforma')),
            ],
            options={
                'verbose_name': 'Mensagem Fraudulenta',
                'verbose_name_plural': 'Mensagens Fraudulentas',
            },
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField(verbose_name='Enunciado')),
                ('alternativa_correta', models.CharField(max_length=100, verbose_name='Alternativa correta')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.quiz', verbose_name='Quiz')),
            ],
            options={
                'verbose_name': 'Pergunta',
                'verbose_name_plural': 'Perguntas',
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('correta', models.BooleanField(verbose_name='Correta')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pergunta', verbose_name='Pergunta')),
            ],
            options={
                'verbose_name': 'Resposta',
                'verbose_name_plural': 'Respostas',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do usuário')),
                ('email', models.EmailField(max_length=254, verbose_name='Email do usuário')),
                ('senha', models.CharField(max_length=50, verbose_name='Senha do usuário')),
                ('idade', models.IntegerField(verbose_name='Idade do usuário')),
                ('tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipousuario', verbose_name='Tipo de usuário')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('data', models.DateTimeField(verbose_name='Data')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
            },
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data', models.DateTimeField(verbose_name='Data')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Denúncia',
                'verbose_name_plural': 'Denúncias',
            },
        ),
    ]
